/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_registrationhandler_free: (a: number, b: number) => void;
export const __wbg_registrationresult_free: (a: number, b: number) => void;
export const registrationresult_export_key: (a: number) => [number, number];
export const registrationresult_server_public_key: (a: number) => [number, number];
export const registrationresult_record: (a: number) => [number, number];
export const registrationhandler_start: (a: number, b: number) => [number, number, number];
export const registrationhandler_finish_registration: (a: number, b: number, c: number) => [number, number, number];
export const registrationhandler_password: (a: number) => [number, number];
export const registrationhandler_request: (a: number) => [number, number];
export const __wbg_loginhandler_free: (a: number, b: number) => void;
export const __wbg_loginresult_free: (a: number, b: number) => void;
export const loginhandler_start: (a: number, b: number) => [number, number, number];
export const loginhandler_finish_login: (a: number, b: number, c: number) => [number, number, number];
export const loginhandler_request: (a: number) => [number, number];
export const loginresult_export_key: (a: number) => [number, number];
export const loginresult_session_key: (a: number) => [number, number];
export const loginresult_serevr_pub_key: (a: number) => [number, number];
export const loginresult_finish_login_request: (a: number) => [number, number];
export const __wbg_resetpasswordhandler_free: (a: number, b: number) => void;
export const resetpasswordhandler_start: (a: number, b: number, c: number, d: number) => [number, number, number];
export const resetpasswordhandler_finish_registration: (a: number, b: number, c: number) => [number, number, number];
export const resetpasswordhandler_password: (a: number) => [number, number];
export const resetpasswordhandler_code: (a: number) => [number, number];
export const resetpasswordhandler_request: (a: number) => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
