//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "server_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub server_setup: String,
    #[sea_orm(column_type = "Text")]
    pub jwt_sign_key: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub server_data: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub server_admin_mail: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub server_admin_appkey: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
